// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw_q0NpQlQTR4OXv2hdrQlYVz3152gtPo',
    appId: '1:596807764872:android:d265d092b8695803af883d',
    messagingSenderId: '596807764872',
    projectId: 'evently-bac27',
    storageBucket: 'evently-bac27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD19hVlCVubgzNeQIXsw48_qBlEsFCOkPg',
    appId: '1:596807764872:ios:05ebbfd7fbcc5979af883d',
    messagingSenderId: '596807764872',
    projectId: 'evently-bac27',
    storageBucket: 'evently-bac27.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWNsHnU5K4Hnf9ceDsu9DlMNYrEW29qhA',
    appId: '1:596807764872:web:a908d598415b9fbdaf883d',
    messagingSenderId: '596807764872',
    projectId: 'evently-bac27',
    authDomain: 'evently-bac27.firebaseapp.com',
    storageBucket: 'evently-bac27.firebasestorage.app',
    measurementId: 'G-ZZRJF3KX6G',
  );
}
